import type { ValueProvenanceRecordDto } from '@/types/backend/inspection'

import { useInspectorStore } from './inspectorStore'

import './InspectorPanels.css'

type ValueProvenancePanelProps = {
  records: ValueProvenanceRecordDto[]
  warnings: string[]
}

export function ValueProvenancePanel({ records, warnings }: ValueProvenancePanelProps) {
  const selectNode = useInspectorStore((state) => state.selectNode)
  const setActiveTab = useInspectorStore((state) => state.setActiveTab)

  return (
    <div className="inspector-provenance">
      {warnings.length ? (
        <ul className="inspector-warnings">
          {warnings.map((warning) => (
            <li key={warning}>{warning}</li>
          ))}
        </ul>
      ) : null}
      {!records.length ? <p className="inspector-empty">No provenance records.</p> : null}
      <ul className="inspector-provenance-list">
        {records.map((record) => (
          <li key={record.display_id}>
            <button
              type="button"
              className="inspector-provenance-row"
              onClick={() => {
                if (record.source_node) {
                  selectNode(record.source_node)
                  setActiveTab('trace')
                }
              }}
            >
              <div className="inspector-provenance-row__value">{record.display_value || record.display_id}</div>
              <div className="inspector-provenance-row__meta">
                <span>{record.source_node || 'missing source'}</span>
                <span>{record.source_property}</span>
              </div>
              {record.generated_by ? <div>Generated by: {record.generated_by}</div> : null}
              {record.consumed_by?.length ? <div>Consumed by: {record.consumed_by.join(', ')}</div> : null}
              {record.missing ? <div className="inspector-trace-step__error">Missing provenance</div> : null}
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
